CREATE SEQUENCE pedido_numero_seq;

CREATE TABLE cartorio (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome        VARCHAR(150) NOT NULL,
    cep         CHAR(8) NOT NULL,
    rua         VARCHAR(150) NOT NULL,
    numero      VARCHAR(20) NOT NULL,
    complemento VARCHAR(100),
    bairro      VARCHAR(100),
    cidade      VARCHAR(100) NOT NULL,
    uf          CHAR(2) NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE documento (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome       VARCHAR(150) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE cartorio_documento (
    cartorio_id   BIGINT NOT NULL,
    documento_id  BIGINT NOT NULL,
    PRIMARY KEY (cartorio_id, documento_id),
    CONSTRAINT fk_cartorio_documento_cartorio
        FOREIGN KEY (cartorio_id) REFERENCES cartorio (id) ON DELETE CASCADE,
    CONSTRAINT fk_cartorio_documento_documento
        FOREIGN KEY (documento_id) REFERENCES documento (id) ON DELETE CASCADE
);

CREATE TABLE pedido (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero      INTEGER NOT NULL UNIQUE DEFAULT nextval('pedido_numero_seq'),
    lead        VARCHAR(200) NOT NULL,
    observacao  TEXT,
    status      VARCHAR(20) NOT NULL DEFAULT 'EM_ANDAMENTO',
    criado_por  VARCHAR(150) NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE agendamento (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id                BIGINT NOT NULL,
    cartorio_id              BIGINT NOT NULL,
    documento_id             BIGINT NOT NULL,
    tipo_pessoa              VARCHAR(20) NOT NULL,
    nome_razao_social        VARCHAR(200) NOT NULL,
    documento_identificacao  VARCHAR(14) NOT NULL,
    data_nascimento          DATE,
    status                   VARCHAR(20) NOT NULL DEFAULT 'PENDENTE',
    created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_agendamento_pedido
        FOREIGN KEY (pedido_id) REFERENCES pedido (id) ON DELETE CASCADE,
    CONSTRAINT fk_agendamento_cartorio
        FOREIGN KEY (cartorio_id) REFERENCES cartorio (id) ON DELETE RESTRICT,
    CONSTRAINT fk_agendamento_documento
        FOREIGN KEY (documento_id) REFERENCES documento (id) ON DELETE RESTRICT
);
